<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright 2005-2006 The Apache Software Foundation or its licensors, as applicable

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!DOCTYPE Test SYSTEM "test.dtd">
<!--
Author: Ilia A. Leviev
Version: $Revision: 1.4 $
-->
<Test
  ID="athrow1001"
  date-of-creation="2005-02-09"
  timeout="1"
  >	
  <Author value="Ilia A. Leviev"/>
  <Description>
    Test checks athrow instruction.
    Instruction athrow throw exception of type of java.lang.Exception, 
    if at the time when exception is caught, 
    there is only reference to the exception in stack - test pass.
    else test fail.
   
    Covered assertions assert_instr2a119 assert_instr2a120 assert_instr2a121 assert_instr2a122 assert_over262 assert_over263 assert_over264
  </Description>

  <Source name="athrow1001n.j"/>

  <Runner ID="Runtime">
    <Param name="toRun" value="org.apache.harmony.vts.test.vm.jvms.share.vmVerifierRun">
			<Option name="run"/>
			<Option name="org.apache.harmony.vts.test.vm.jvms.instructions.exceptions.athrow.athrow10.athrow1001.athrow1001n"/>
			<Option name="java.lang.VerifyError"/>
	</Param>
</Runner>
</Test>
