<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright 2005-2006 The Apache Software Foundation or its licensors, as applicable

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!DOCTYPE Test SYSTEM "test.dtd">
<!--
Author:  Alexander D. Shipilov
Version: $Revision: 1.3 $
-->
<Test
  ID="new0201"
  date-of-creation="2004-11-24"
  timeout="1"
  >
  <Author value="Alexander D. Shipilov"/>
  <Description>
    Tests new java virtual machine instruction.
    Creating new object which implemented Exception. Then throwing it.
    If this object created correctly, catcher will catch it.
    Covered assertions assert_class760 assert_instr210a004 assert_instr210a005 assert_instr210a006 assert_instr210a007 assert_instr210a008
  Covered assertions
  </Description> 

  <Source name="new0201p.j"/>

  <Runner ID="Runtime">
    <Param name="toRun" value="org.apache.harmony.vts.test.vm.jvms.instructions.reftypes.new.new02.new0201.new0201p"/>
  </Runner>
</Test>
