<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='../../../../../../../../../../test.xsl'?>
<!--
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!DOCTYPE Test SYSTEM '../../../../../../../../../../test.dtd'>
<Test
    ID="F_ExceptionTest_03"
    date-of-creation="2005-10-17"
    timeout="5"
    >
    <!--
    -->
        
        
        <APITestDescription>
            <TestedClass name="java.lang.AssertionError"/>
            <TestedMethod name="public AssertionError()"/>
            <TestedMethod name="public AssertionError(Object detailMessage)"/>
            <TestedMethod name="public AssertionError(boolean detailMessage)"/>
            <TestedMethod name="public AssertionError(char detailMessage)"/>
            <TestedMethod name="public AssertionError(int detailMessage)"/>
            <TestedMethod name="public AssertionError(long detailMessage)"/>
            <TestedMethod name="public AssertionError(float detailMessage)"/>
            <TestedMethod name="public AssertionError(double detailMessage)"/>
            
            <TestedClass name="java.lang.RuntimeException"/>
            <TestedMethod name="public RuntimeException(String message, Throwable cause)"/>
            <TestedMethod name="public RuntimeException(Throwable cause)"/>
            
            <TestedClass name="java.lang.Error"/>
            <TestedMethod name="public Error(String message, Throwable cause)"/>
            <TestedMethod name="public Error(Throwable cause)"/>            
            
            <TestedClass name="java.lang.UnsupportedClassVersionError"/>
            <TestedMethod name="public UnsupportedClassVersionError()"/>
            <TestedMethod name="public UnsupportedClassVersionError(String s)"/>
            
            <TestedClass name="java.lang.VirtualMachineError"/>
            <TestedMethod name="public VirtualMachineError()"/>
            <TestedMethod name="public VirtualMachineError(String s)"/>
            
            <TestedClass name="java.lang.UnsupportedOperationException"/>
            <TestedMethod name="public UnsupportedOperationException()"/>
            <TestedMethod name="public UnsupportedOperationException(String message)"/>
                        
            <TestedClass name="java.lang.StackTraceElement"/>
            <TestedMethod name="public boolean equals(Object obj)"/>
            <TestedMethod name="public int hashCode()"/>            
            
            <Description>
            </Description>
        </APITestDescription>

        <Keyword name="functional"/>
        <Source name="F_ExceptionTest_03.java"/>
        <Modification date="2005-10-17" />

        <Runner ID="Runtime">
                <Param name="toRun" value="org.apache.harmony.test.func.api.java.lang.F_ExceptionTest_03.F_ExceptionTest_03">
            </Param>
        </Runner>
</Test> 